name: Print out Hello from the other side

on:
  workflow_call:
    inputs:
      myname:
        required: true
        type: string 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello from the other side ${{ inputs.myname }}!"
    
